avitorio/outstatic

apps/web/outstatic/content/docs/introduction.md
This PR suggests some grammar fixes and wording changes for the Introduction page of the docs.
=> docs: grammar fixes for Introduction

apps/web/outstatic/content/docs/getting-started.md, packages/outstatic/src/pages/list.tsx, packages/outstatic/src/pages/settings.tsx
This PR adds a branch field to the Settings page, as well as other improvements to docs and linting.
=> feat: additions to (Add branch name configuration #2)

packages/outstatic/src/components/Alert/index.tsx, packages/outstatic/src/pages/collections.tsx, packages/outstatic/src/pages/edit-collection/index.tsx, packages/outstatic/src/pages/list.tsx, packages/outstatic/src/pages/settings.tsx
Display an error when a collection can't be created. Based on https://github.com/avitorio/outstatic/issues/17
=> feat: inexistent branch error

.github/pull_request_template.md, CONTRIBUTING.md, packages/outstatic/README.md
This PR refers to #58
It covers: 
- Initial CONTRIBUTING.md file
- Initial pull_request_template.md
- Addition to contributing link to the README
=> Create contributing guidelines.

packages/outstatic/src/components/DocumentSettingsImageSelection/index.tsx, packages/outstatic/src/pages/api/images/index.ts, packages/outstatic/src/pages/edit-document/index.tsx, packages/outstatic/src/utils/assertUnreachable.ts, packages/outstatic/src/utils/constants.ts, packages/outstatic/src/utils/createCommitInput.ts, packages/outstatic/src/utils/escapeRegExp.ts, packages/outstatic/src/utils/mergeMdMeta.ts
=> chore: Extract images path constant

packages/outstatic/package.json, packages/outstatic/src/components/DocumentSettings/index.tsx, packages/outstatic/src/components/TagInput/index.tsx, packages/outstatic/src/pages/add-custom-field/index.tsx, packages/outstatic/src/pages/edit-document/index.tsx, packages/outstatic/src/types/index.ts, packages/outstatic/src/utils/mergeMdMeta.ts, pnpm-lock.yaml
=> feat: add Tags custom field

examples/blog/src/app/api/outstatic/[[...ost]]/route.ts, examples/blog/src/app/outstatic/[[...ost]]/page.tsx, examples/blog/src/pages/api/outstatic/[[...ost]].tsx, examples/blog/src/pages/outstatic/[[...ost]].tsx
=> feat: update example blog to 1.0.0-canary.1

apps/dev/package.json, apps/web/outstatic/content/docs/getting-started.md, apps/web/package.json, examples/blog/package.json, pnpm-lock.yaml
- remove @tiptap/pm from apps and example blog
=> feat: remove @tiptap/pm from apps and example blog

apps/web/outstatic/content/docs/local-development.md, apps/web/outstatic/content/menus/docs-menu.md, apps/web/outstatic/content/metadata.json
----
When I tried to run Outstatic locally, it took me some time to get it to work. I hope this documentation is helpful for new users.
=> chore: Doc for local development

.changeset/strange-kids-glow.md, packages/outstatic/src/app/api/auth/callback.ts, packages/outstatic/src/client/pages/login.tsx, packages/outstatic/src/utils/errors/loginErrors.ts
This was done to prevent users who are not collaborators in the repo to sign in to the dashboard.
REQUIREMENTS:
OST_REPO_OWNER has to be set to a value in order for the api request to be valid. Therefore, with this code, it is no longer an optional environmental variable.
=> Added a checker function to see if the user is a collaborator

.changeset/witty-balloons-check.md, packages/outstatic/src/client/pages/collections.tsx
=> feat: improve collections card ux

.changeset/nasty-mice-lie.md, packages/outstatic/src/client/pages/collections.tsx, packages/outstatic/src/components/AdminHeader/index.tsx, packages/outstatic/src/components/AdminLayout/index.tsx, packages/outstatic/src/components/DeleteDocumentButton/index.tsx, packages/outstatic/src/components/DocumentSettings/index.tsx, packages/outstatic/src/components/Modal/index.tsx, packages/outstatic/src/components/Sidebar/index.tsx
=> feat: improve mobile experience

.changeset/khaki-coats-learn.md, packages/outstatic/src/client/pages/list.tsx, packages/outstatic/src/utils/editor/extensions/SlashCommand.tsx
=> fix: 186-cover-image

apps/dev/package.json, pnpm-lock.yaml
=> chore: hard set nextjs 14

packages/outstatic/src/utils/server.ts
=> fix: getDocumens null error

.changeset/serious-melons-wave.md, apps/dev/src/app/(web)/[...slug]/page.tsx, apps/dev/src/app/(web)/page.tsx, apps/dev/src/styles/index.css, apps/dev/tailwind.config.js, examples/advanced-blog/src/app/(web)/[...slug]/page.tsx, examples/advanced-blog/src/app/(web)/page.tsx, examples/advanced-blog/src/styles/index.css, examples/advanced-blog/tailwind.config.js
=> feat: add onload animation

.changeset/pink-camels-tan.md, packages/outstatic/src/utils/editor/utils/addImage.ts
=> fix: blob type error

apps/docs/outstatic/content/docs/fetching-data.md, examples/docs/outstatic/content/docs/fetching-data.md
Fixes out-of-date documentation links.
=> fix(docs): update out-of-date link

packages/outstatic/src/components/DocumentsTable/index.tsx, packages/outstatic/src/components/DocumentsTable/test.tsx, packages/outstatic/src/utils/hooks/useSortedDocuments.tsx
Fixes the document sorting issue and adds related test cases.
https://github.com/avitorio/outstatic/assets/3916436/65cec752-703b-4970-9b04-89b448f83cc9
=> Fix Document Sorting

apps/docs/outstatic/content/collections.json, apps/docs/outstatic/content/docs/getting-started.md, apps/docs/outstatic/content/metadata.json, outstatic/config.json
=> Update Docs (#260)

.changeset/chilly-turkeys-compete.md, apps/dev/src/app/(cms)/outstatic/[[...ost]]/page.tsx, apps/docs/outstatic/content/docs/getting-started.md, apps/docs/outstatic/content/metadata.json, packages/outstatic/package.json, packages/outstatic/src/app/api/auth/signout.ts, packages/outstatic/src/app/api/index.tsx, packages/outstatic/src/utils/auth/auth-cookies.ts, packages/outstatic/src/utils/auth/auth.ts, packages/outstatic/src/utils/constants.ts, pnpm-lock.yaml
This PR adds support for Next.js 15 on v1.4
=> feat: add nextjs 15 support for v1.4

apps/dev/next-env.d.ts, apps/dev/package.json, apps/docs/next-env.d.ts, apps/docs/package.json, examples/advanced-blog/package.json, examples/basic-blog/package.json, examples/docs/next-env.d.ts, examples/docs/package.json, examples/outstatic-dashboard/package.json, pnpm-lock.yaml
=> chore: up react 19, next 15.2.4

.changeset/four-onions-invite.md, packages/outstatic/package.json
Add correct peer dependencies for v2
=> chore: add correct peer dependencies for v2

.changeset/sharp-zebras-taste.md, apps/dev/src/app/(cms)/layout.tsx, apps/docs/outstatic/content/docs/getting-started-with-next-js.mdx, apps/docs/outstatic/content/docs/upgrading-to-v2.0.mdx, apps/docs/src/app/(cms)/layout.tsx, examples/advanced-blog/src/app/(cms)/layout.tsx, examples/basic-blog/src/app/(cms)/layout.tsx, examples/docs/outstatic/content/docs/getting-started-with-next-js.mdx, examples/docs/outstatic/content/docs/upgrading-to-v2.0.mdx, examples/docs/src/app/(cms)/layout.tsx, examples/outstatic-dashboard/src/app/(cms)/layout.tsx, examples/outstatic-dashboard/src/app/layout.tsx
Fix based on the docs for `next-themse`
https://github.com/pacocoursey/next-themes?tab=readme-ov-file#with-app
=> fix: next-themes hydration error

.changeset/quick-heads-watch.md, packages/outstatic/src/components/editor/extensions/slash-command/ImageCommandList.tsx, packages/outstatic/src/components/ui/outstatic/media-library-header.tsx, packages/outstatic/src/components/ui/outstatic/media-library-modal.tsx
- Media library dialog is too narrow
- Add some contrast to command menu descriptions
=> fix: media gallery dialog

.changeset/rare-bears-see.md, packages/outstatic/src/components/DocumentSettings/custom-field-renderer.tsx, packages/outstatic/src/components/DocumentSettings/index.tsx, packages/outstatic/src/components/ui/shadcn/accordion.tsx, pnpm-lock.yaml
Add shadcn/ui accordion to custom fields
=> feat: add shadcn/ui accordion to custom fields

.changeset/red-taxis-kneel.md, packages/outstatic/src/client/pages/custom-fields/_components/add-custom-field-dialog.tsx, packages/outstatic/src/client/pages/custom-fields/_components/edit-custom-field-dialog.tsx
=> fix: dialog widths

.changeset/icy-zoos-matter.md, packages/outstatic/src/client/pages/collections/_components/new-collection-modal.tsx, packages/outstatic/src/components/ui/outstatic/line-background.tsx
feat: fix new collection content clock
=> feat: fix new collection content clock
