- apps/web/src/pages/docs/[slug].tsx
This PR removes the period from the “Last updated…” metadata line in the docs.
> docs: rm `.` from "Last updated" metadata display

- .github/ISSUE_TEMPLATE/config.yml
Inspired by TailwindCSS: https://github.com/tailwindlabs/tailwindcss/blob/master/.github/ISSUE_TEMPLATE/config.yml
You can preview the UI in my fork here: https://github.com/DCzajkowski/outstatic/issues/new/choose
This will limit accidental issues, that should be in discussions (like #43)
> feat: block github issues not-relating to confirmed bugs

- apps/dev/package.json
- examples/blog/package.json
- packages/outstatic/package.json
- turbo.json
This adds linting to the `/packages/outstatic` project and also to the example and dev blogs.
> chore: add missing lint scripts

- .husky/pre-commit
`--shell` is carryover from older lint-staged versions, where tasks weren't parsed. This removes the `--shell` command.
This also removes `FORCE_COLOR` for better error message compatibility with github desktop
> chore: Removes --shell and color from lint-staged

- packages/outstatic/src/pages/api/images/index.ts
- [ x ] Related issues linked using `fixes #85`
> fix: use OST_REPO_OWNER instead of current logged in user for image URLs when set

- packages/outstatic/src/components/DeleteDocumentButton/index.tsx
- packages/outstatic/src/pages/edit-document/index.tsx
Previously when saving/creating a post it was: 
- duplicated in the metadata.json
- missing the 'status' field
- incorrectly referencing the cover image (blob: url instead of actual link if uploaded)
> fix: metadata parity on post save

- packages/outstatic/src/utils/slugRegex.test.ts
- packages/outstatic/src/utils/slugRegex.ts
- packages/outstatic/src/utils/yup.ts
Currently, this schema validation for document slugs:
```js
.matches(
/^[a-z](-?[a-z])*$/,
'Slugs can only start and end with a letter and cannot contain two dashes in a row.'
)
```
does not allow for any numbers in the middle of a slug. I don't see a reason for it to exist, there is already another validation for making sure it only contains valid characters. Is there a reason it was there or can it just be removed?
> fix: remove unneeded slug yup validation

- apps/web/outstatic/content/docs/fetching-data.md
fix the docs [fetching data](https://outstatic.com/docs/fetching-data) code block.
```jsx
// error:  Unexpected token `h1`. Expected jsx identifier
return posts.map((post) => <h1>{post.title}</h1)
```
fix the jsx  identifier error in docs
```jsx
return posts.map((post) => <h1>{post.title}</h1>)
```
> fix the Unexpected token `h1` error in jsx

- apps/web/outstatic/content/docs/getting-started.md
- apps/web/outstatic/content/docs/github-applications.md
- apps/web/outstatic/content/docs/github-apps-authentication.md
- apps/web/outstatic/content/metadata.json
- packages/outstatic/src/app/api/auth/login.ts
Currently, the Outstatic documentation says to create an Oauth application to manage user authentication. 
This is great but GitHub recommends the usage of GitHub application instead which provides Fine Grained access to resources and can limit Outstatic accesses to a single repository (if needed). 
**Changes :** 
- Documentation about GitHub Application added
- Reduce OAuth scopes to only "read:user" and "repo"
> fix(oauth-scopes): reduce required scopes to the minimum

- .changeset/yellow-months-own.md
- packages/outstatic/src/app/api/auth/callback.ts
- packages/outstatic/src/utils/errors/loginErrors.tsx
> feat: add isCollaborator check

- .changeset/flat-comics-clean.md
- packages/outstatic/src/client/pages/collections.tsx
Use OST_REPO_OWNER when deleting a collection. 
Otherwise breaks deleting a collection if Repo Owner is different than logged in user. 
See image for current error (endless spinning when trying to delete)
> Use OST_REPO_OWNER when deleting a collection

- .changeset/shiny-hats-knock.md
- packages/outstatic/src/components/DocumentSettingsImageSelection/index.tsx
ShowImage boolean was being set to true before the file is read. This triggered the OnError() callback of the img tag in Safari.
Below are screenshots of what the console looked like when the setShowImage(true) was there (I added logs for tracing):
Safari
Chrome
For some reason Google Chrome, does not complain about this.
After removing the extra setShowImage(true) line, upload cover image using a file works for both Chrome and Safari.
- [x ] Related issues linked using `fixes #135`
> fix: upload Cover Image file error for Safari Browser

- apps/web/src/app/layout.tsx
Typo fix, the metadata has `dabatase` instead of `database`.
> fix: metadata typo

- .changeset/hot-dragons-fix.md
- packages/outstatic/src/components/DocumentSettings/index.tsx
- packages/outstatic/src/components/DocumentSettings/test.tsx
- packages/outstatic/src/utils/TestWrapper.tsx
- packages/outstatic/src/utils/hooks/useDocumentUpdateEffect.tsx
1. Actual code change is very light, a lot of the PR comes from me trying to replicate the test case to prove the change worked
```sh
packages/outstatic/src/components/DocumentSettings/index.tsx
packages/outstatic/src/utils/hooks/useDocumentUpdateEffect.tsx
```
2. `<TestWrapper>` extensions
I just extended the providers to be accessible so that if I want to manipulate them in my test, it's easier to do so (happy though to follow your lead on this). My end goal is to just show that when the payload received is `undefined`, the component is resilent enough to take cafe of it.
3. I didn't touch the code at the mutation level (so `setLoginSession`) cause I wasn't sure if there's any other side effect of `author.name` being `undefined` might bring. So instead I opted in to handle it at the …
> fix: author name check

- .changeset/brave-crabs-swim.md
- packages/outstatic/src/client/pages/add-custom-field/index.tsx
- packages/outstatic/src/client/pages/collections.tsx
- packages/outstatic/src/components/DeleteDocumentButton/index.tsx
- packages/outstatic/src/components/MetadataBuilder/index.tsx
- packages/outstatic/src/utils/createCommitApi.ts
- packages/outstatic/src/utils/hooks/useSubmitDocument.tsx
> feat: remove collections from metadata db

- .changeset/six-teachers-shake.md
- packages/outstatic/src/utils/editor/extensions/index.tsx
Linkify is breaking pages as it's invalid GFM
> fix: don't auto create links from 'https://'

- .changeset/spicy-apples-give.md
- packages/outstatic/src/components/DocumentSettings/index.tsx
Removed a double border in post aside:
**Before:**
https://github.com/avitorio/outstatic/assets/13696888/39126077-cfe6-4a79-95cb-501449449004
**After:**
https://github.com/avitorio/outstatic/assets/13696888/334cf9b1-ee1e-45a5-bef1-30301cc935cc
Not sure if this requires any tests or issues to be opened, if so let me know!
> fix: Remove double border in aside

- examples/advanced-blog/src/app/(web)/[...slug]/page.tsx
- examples/advanced-blog/src/lib/mdx-server.ts
First of all thank you for this sleek template, I loved it so much that I wanted to make a contribution to your project. I was running the site on my local machine with "npm run dev" without any problem. But when I tried to deploy it on vercel, I realized that there are some errors which is preventing the build process. I will upload screenshot of it below.
After this error, I spent some time to resolve it and here is the description of what I have done. *Just keep in mind that front-end is not my field, I just fixed it because I loved it :D so you can make as much as modification as you want.*
This pull request addresses several TypeScript errors that were occurring during the build process in the `mdx-server.ts` file. The errors prevented successful compilation and affected the handling …
> fixed build errors caused by mdx-server.ts and page.tsx under the example/advanced-blog

- .changeset/perfect-berries-battle.md
- packages/outstatic/package.json
- packages/outstatic/src/components/Sidebar/index.tsx
- packages/outstatic/src/components/ui/tooltip.tsx
- pnpm-lock.yaml
- [ x] Implements an existing feature request or RFC. Make sure the feature request has been accepted for implementation before opening a PR.
Implemented a quick add button that was suggested and designed by @praveenjuge.
> feat: implement a quick add button

- .changeset/fresh-apricots-appear.md
- packages/outstatic/package.json
- packages/outstatic/src/client/pages/add-custom-field.tsx
- packages/outstatic/src/components/DocumentSettings/index.tsx
- packages/outstatic/src/components/ui/checkbox-with-label.tsx
- packages/outstatic/src/components/ui/checkbox.tsx
- packages/outstatic/src/components/ui/input.tsx
- packages/outstatic/src/types/index.ts
- pnpm-lock.yaml
> add boolean for custom fields
